[toolchain]
# remember to update in GitHub Actions workflow file
channel = "nightly-2022-11-17"
targets = ["wasm32-unknown-unknown"]
profile = "minimal"
components = ["clippy", "rustfmt", "rust-src"]
